/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gpa.calculator;

import java.awt.Color;
import java.io.File;
import java.io.IOException;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.Scanner;
import javax.swing.*;
import javax.swing.border.Border;

/**
 *
 * @author Jonathan
 */
public class calc extends javax.swing.JFrame {

    /**
     * Creates new form calc
     */
    
    private int fives;
    private int fours;
    private int threes;
    private int semesters;
    private int addedFives;
    private int addedFours;
    private int addedThrees;
    private double gpa;
    
    public calc() {
        super("GPA Calculator by Jonathan Lin");
        initComponents();
        
        ArrayList<String> input;
        try {
        input = new ArrayList<String>();
        Scanner scanner = new Scanner(new File("info.txt"));
        while (scanner.hasNextLine())    {
            input.add(scanner.nextLine());
        }
        } catch (IOException e) {
            System.out.println("Error: " + e);
            input = null;
        }
        
        fives = (Integer.parseInt(input.get(0)));
        fours = (Integer.parseInt(input.get(1)));
        threes = (Integer.parseInt(input.get(2)));
        semesters = fives + fours + threes;
        gpa = 4.66666;
        
        update();
        DecimalFormat df = new DecimalFormat("#.####");
        originalgpa.setText("Original GPA: " + df.format(gpa));
        
        Border blackline = BorderFactory.createLineBorder(Color.white,2);
        add5.setBorder(blackline);
        add4.setBorder(blackline);
        add3.setBorder(blackline);
        minus5.setBorder(blackline);
        minus4.setBorder(blackline);
        minus3.setBorder(blackline);
    }
    
    private void update(){
        label3.setText("Added 5s: " + String.valueOf(addedFives));
        label4.setText("Added 4s: " + String.valueOf(addedFours));
        label5.setText("Added 3s: " + String.valueOf(addedThrees));
        DecimalFormat df = new DecimalFormat("#.####");
        
        gpa = (5*fives) + (4*fours) + (3*threes);
        gpa = gpa / semesters;
        gpaDisplay.setText(df.format(gpa));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        gpaDisplay = new javax.swing.JLabel();
        label3 = new javax.swing.JLabel();
        label4 = new javax.swing.JLabel();
        label5 = new javax.swing.JLabel();
        add5 = new javax.swing.JLabel();
        minus5 = new javax.swing.JLabel();
        add4 = new javax.swing.JLabel();
        minus4 = new javax.swing.JLabel();
        add3 = new javax.swing.JLabel();
        minus3 = new javax.swing.JLabel();
        originalgpa = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 0, 51));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        gpaDisplay.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        gpaDisplay.setForeground(new java.awt.Color(255, 255, 255));
        gpaDisplay.setText("4.5");

        label3.setForeground(new java.awt.Color(255, 255, 255));
        label3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label3.setText("Added 5s: 0");

        label4.setForeground(new java.awt.Color(255, 255, 255));
        label4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label4.setText("Added 4s: 4");

        label5.setForeground(new java.awt.Color(255, 255, 255));
        label5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label5.setText("Added 3s: 2");

        add5.setBackground(new java.awt.Color(0, 255, 0));
        add5.setForeground(new java.awt.Color(0, 0, 0));
        add5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add5.setText("+ 5");
        add5.setOpaque(true);
        add5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                add5MouseClicked(evt);
            }
        });

        minus5.setBackground(new java.awt.Color(255, 51, 51));
        minus5.setForeground(new java.awt.Color(0, 0, 0));
        minus5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        minus5.setText("- 5");
        minus5.setOpaque(true);
        minus5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minus5MouseClicked(evt);
            }
        });

        add4.setBackground(new java.awt.Color(0, 255, 0));
        add4.setForeground(new java.awt.Color(0, 0, 0));
        add4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add4.setText("+ 4");
        add4.setOpaque(true);
        add4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                add4MouseClicked(evt);
            }
        });

        minus4.setBackground(new java.awt.Color(255, 51, 51));
        minus4.setForeground(new java.awt.Color(0, 0, 0));
        minus4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        minus4.setText("- 4");
        minus4.setOpaque(true);
        minus4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minus4MouseClicked(evt);
            }
        });

        add3.setBackground(new java.awt.Color(0, 255, 0));
        add3.setForeground(new java.awt.Color(0, 0, 0));
        add3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add3.setText("+ 3");
        add3.setOpaque(true);
        add3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                add3MouseClicked(evt);
            }
        });

        minus3.setBackground(new java.awt.Color(255, 51, 51));
        minus3.setForeground(new java.awt.Color(0, 0, 0));
        minus3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        minus3.setText("- 3");
        minus3.setOpaque(true);
        minus3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minus3MouseClicked(evt);
            }
        });

        originalgpa.setForeground(new java.awt.Color(255, 255, 255));
        originalgpa.setText("Original GPA: 4.3");

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Note: everything is counted by semesters, not years");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Predicted GPA: ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(0, 0, 0)
                                .addComponent(gpaDisplay))
                            .addComponent(originalgpa))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(minus5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(minus4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(minus3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, 0)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(add3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(add4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(add5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(45, 45, 45))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(29, 29, 29))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(minus5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(add5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, 0)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(minus4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(add4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, 0)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(minus3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(add3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(gpaDisplay))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(originalgpa)
                        .addGap(34, 34, 34)
                        .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void add5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_add5MouseClicked
        // TODO add your handling code here:
        fives++;
        addedFives++;
        semesters++;
        update();
    }//GEN-LAST:event_add5MouseClicked

    private void add4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_add4MouseClicked
        // TODO add your handling code here:
        fours++;
        addedFours++;
        semesters++;
        update();
    }//GEN-LAST:event_add4MouseClicked

    private void add3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_add3MouseClicked
        // TODO add your handling code here:
        threes++;
        addedThrees++;
        semesters++;
        update();
    }//GEN-LAST:event_add3MouseClicked

    private void minus5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minus5MouseClicked
        // TODO add your handling code here:
        fives--;
        addedFives--;
        semesters--;
        update();
    }//GEN-LAST:event_minus5MouseClicked

    private void minus4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minus4MouseClicked
        // TODO add your handling code here:
        fours--;
        addedFours--;
        semesters--;
        update();
    }//GEN-LAST:event_minus4MouseClicked

    private void minus3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minus3MouseClicked
        // TODO add your handling code here:
        threes--;
        addedThrees--;
        semesters--;
        update();
    }//GEN-LAST:event_minus3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(calc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(calc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(calc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(calc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new calc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel add3;
    private javax.swing.JLabel add4;
    private javax.swing.JLabel add5;
    private javax.swing.JLabel gpaDisplay;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel label3;
    private javax.swing.JLabel label4;
    private javax.swing.JLabel label5;
    private javax.swing.JLabel minus3;
    private javax.swing.JLabel minus4;
    private javax.swing.JLabel minus5;
    private javax.swing.JLabel originalgpa;
    // End of variables declaration//GEN-END:variables
}
